/**
 * Context Windowing — Auto-summarization of old session messages.
 *
 * When a session's message history exceeds a configurable threshold,
 * older messages are summarized into a compact summary and the originals
 * are dropped. This keeps token usage bounded without losing important context.
 *
 * The summarization is deterministic: given the same messages and options,
 * it produces the same summary structure. The actual summary text can be
 * generated by an LLM (via a supplied callback) or by a built-in extractive
 * fallback that preserves key decisions and artifacts.
 */

import type { SessionMessage } from '../server/agent-lifecycle.js';

// ============================================================================
// Types
// ============================================================================

export interface ContextWindowConfig {
  /** Maximum number of messages before triggering summarization. Default: 50 */
  maxMessages: number;
  /** Number of recent messages to always keep verbatim (the "tail"). Default: 10 */
  keepRecent: number;
  /** Maximum character length for the generated summary. Default: 2000 */
  maxSummaryLength: number;
  /**
   * Optional LLM-based summarizer. If not provided, the built-in extractive
   * summarizer is used. The function receives the messages to summarize and
   * should return a compact summary string.
   */
  summarizer?: (messages: SessionMessage[]) => Promise<string>;
}

export interface ContextWindowState {
  /** Number of summarization passes that have occurred */
  summarizationCount: number;
  /** Running summary of all previously summarized messages */
  summary: string;
  /** Cursor: timestamp of the most recently summarized message */
  summarizedUpTo: string | null;
  /** Total messages that have been summarized away */
  totalSummarizedMessages: number;
}

export interface WindowResult {
  /** Messages to keep in the session (summary message + recent tail) */
  messages: SessionMessage[];
  /** Updated window state after this pass */
  state: ContextWindowState;
  /** Whether summarization was triggered on this call */
  summarized: boolean;
  /** Number of messages that were compressed in this pass */
  compressedCount: number;
}

// ============================================================================
// Defaults
// ============================================================================

export const DEFAULT_CONTEXT_WINDOW_CONFIG: ContextWindowConfig = {
  maxMessages: 50,
  keepRecent: 10,
  maxSummaryLength: 2000,
};

export function createContextWindowState(): ContextWindowState {
  return {
    summarizationCount: 0,
    summary: '',
    summarizedUpTo: null,
    totalSummarizedMessages: 0,
  };
}

// ============================================================================
// Extractive Summarizer (built-in, no LLM needed)
// ============================================================================

/**
 * Extract key information from messages without an LLM.
 * Preserves: decisions, errors, artifacts, blockers, and key conclusions.
 * Drops: routine progress updates, verbose tool output, duplicated context.
 */
export function extractiveSummarize(
  messages: SessionMessage[],
  maxLength: number,
): string {
  if (messages.length === 0) return '';

  const keyLines: string[] = [];

  // Extract time range
  const first = messages[0];
  const last = messages[messages.length - 1];
  if (first && last) {
    keyLines.push(
      `[Summary of ${messages.length} messages from ${first.timestamp} to ${last.timestamp}]`,
    );
  }

  // Count by role
  const userCount = messages.filter(m => m.role === 'user').length;
  const assistantCount = messages.filter(m => m.role === 'assistant').length;
  keyLines.push(`Exchanges: ${userCount} user messages, ${assistantCount} assistant responses.`);

  // Extract high-signal content patterns
  const patterns: Record<string, RegExp> = {
    decisions: /(?:decided|decision|agreed|confirmed|approved|rejected|blocked)/i,
    errors: /(?:error|failed|failure|exception|bug|crash|broken)/i,
    artifacts: /(?:created|wrote|generated|built|deployed|published|committed)/i,
    questions: /(?:\?$|question:|unclear|need to know|which|should we)/im,
  };

  const extracted: Record<string, string[]> = {
    decisions: [],
    errors: [],
    artifacts: [],
    questions: [],
  };

  for (const msg of messages) {
    const lines = msg.content.split('\n').filter(l => l.trim().length > 0);
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.length < 10 || trimmed.length > 500) continue;

      for (const [category, pattern] of Object.entries(patterns)) {
        if (pattern.test(trimmed) && extracted[category]!.length < 5) {
          extracted[category]!.push(`- ${trimmed.slice(0, 200)}`);
        }
      }
    }
  }

  for (const [category, items] of Object.entries(extracted)) {
    if (items.length > 0) {
      const label = category.charAt(0).toUpperCase() + category.slice(1);
      keyLines.push(`\n${label}:`);
      keyLines.push(...items);
    }
  }

  const result = keyLines.join('\n');
  if (result.length <= maxLength) return result;
  return result.slice(0, maxLength - 3) + '...';
}

// ============================================================================
// Context Window Engine
// ============================================================================

/**
 * Apply context windowing to a session's message history.
 *
 * If the message count exceeds `config.maxMessages`, the older messages
 * (everything except the most recent `config.keepRecent`) are summarized
 * and replaced with a single system message containing the summary.
 *
 * The function is pure: it returns new arrays, it does not mutate the inputs.
 */
export async function applyContextWindow(
  messages: SessionMessage[],
  state: ContextWindowState,
  config: Partial<ContextWindowConfig> = {},
): Promise<WindowResult> {
  const cfg: ContextWindowConfig = { ...DEFAULT_CONTEXT_WINDOW_CONFIG, ...config };

  // Guard: keepRecent must be less than maxMessages
  if (cfg.keepRecent >= cfg.maxMessages) {
    cfg.keepRecent = Math.max(1, Math.floor(cfg.maxMessages / 2));
  }

  // Not enough messages to trigger — return unchanged
  if (messages.length <= cfg.maxMessages) {
    return {
      messages: [...messages],
      state: { ...state },
      summarized: false,
      compressedCount: 0,
    };
  }

  // Split: messages to summarize vs. messages to keep
  const splitIndex = messages.length - cfg.keepRecent;
  const toSummarize = messages.slice(0, splitIndex);
  const toKeep = messages.slice(splitIndex);

  // Generate summary — use LLM summarizer if provided, else extractive
  let newSummaryBlock: string;
  if (cfg.summarizer) {
    try {
      newSummaryBlock = await cfg.summarizer(toSummarize);
    } catch {
      // Fallback to extractive if LLM fails
      newSummaryBlock = extractiveSummarize(toSummarize, cfg.maxSummaryLength);
    }
  } else {
    newSummaryBlock = extractiveSummarize(toSummarize, cfg.maxSummaryLength);
  }

  // Truncate if needed
  if (newSummaryBlock.length > cfg.maxSummaryLength) {
    newSummaryBlock = newSummaryBlock.slice(0, cfg.maxSummaryLength - 3) + '...';
  }

  // Combine with any prior summary
  const combinedSummary = state.summary
    ? `${state.summary}\n\n---\n\n${newSummaryBlock}`
    : newSummaryBlock;

  // Enforce max length on combined summary too
  const finalSummary = combinedSummary.length > cfg.maxSummaryLength * 2
    ? combinedSummary.slice(-cfg.maxSummaryLength * 2)
    : combinedSummary;

  // Build the summary system message
  const summaryMessage: SessionMessage = {
    role: 'system',
    content: `[Context Summary — ${state.summarizationCount + 1} pass(es), ${state.totalSummarizedMessages + toSummarize.length} messages compressed]\n\n${finalSummary}`,
    timestamp: new Date().toISOString(),
  };

  const lastSummarized = toSummarize[toSummarize.length - 1];
  const newState: ContextWindowState = {
    summarizationCount: state.summarizationCount + 1,
    summary: finalSummary,
    summarizedUpTo: lastSummarized?.timestamp ?? state.summarizedUpTo,
    totalSummarizedMessages: state.totalSummarizedMessages + toSummarize.length,
  };

  return {
    messages: [summaryMessage, ...toKeep],
    state: newState,
    summarized: true,
    compressedCount: toSummarize.length,
  };
}
